# Generated by Django 4.2.7 on 2023-11-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=34, unique=True)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
