# Generated by Django 4.2.7 on 2023-11-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=35)),
                ('quantity', models.IntegerField(max_length=20)),
                ('status', models.CharField(max_length=35)),
                ('brand', models.IntegerField(max_length=40)),
            ],
        ),
    ]
