# Generated by Django 4.2.7 on 2023-11-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_alter_product_brand_alter_product_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
