# Generated by Django 4.2.7 on 2023-11-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=35)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=35)),
                ('brand', models.IntegerField()),
            ],
        ),
    ]
