# Generated by Django 4.2.7 on 2023-11-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_brands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
