# Generated by Django 4.2.7 on 2023-11-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_rename_product_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productimg',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
