# Generated by Django 4.2.7 on 2023-11-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_products_productimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productimg',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
