# Generated by Django 4.2.7 on 2023-11-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_products_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
