# Generated by Django 4.2.7 on 2023-11-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='registeruser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('confirmpassword', models.CharField(max_length=128)),
            ],
        ),
    ]
