# Generated by Django 4.2.7 on 2023-11-30 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_registeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='phone_number',
            field=models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
