# Generated by Django 4.2.7 on 2023-12-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_carts_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='productdetails',
        ),
        migrations.AddField(
            model_name='carts',
            name='productdetails',
            field=models.ManyToManyField(to='homepage.carts'),
        ),
    ]
