# Generated by Django 4.2.7 on 2023-12-04 13:18

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_remove_carts_productdetails_carts_productdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='productdetails',
        ),
        migrations.AddField(
            model_name='carts',
            name='productdetails',
            field=models.CharField(default=0, max_length=120, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
