# Generated by Django 4.2.7 on 2023-12-04 13:20

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_remove_carts_productdetails_carts_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='productdetails',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
