# Generated by Django 4.2.7 on 2023-12-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_alter_carts_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
