# Generated by Django 4.2.7 on 2023-12-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_carts_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='qty',
            field=models.CharField(max_length=4),
        ),
    ]
