# Generated by Django 4.2.7 on 2023-12-07 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_alter_carts_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.CharField(max_length=255)),
                ('billing_city', models.CharField(max_length=35)),
                ('billing_postcode', models.IntegerField()),
                ('billing_phonenumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('billing_email', models.EmailField(max_length=254, unique=True)),
                ('shipping_address', models.CharField(max_length=255)),
                ('shipping_city', models.CharField(max_length=35)),
                ('shipping_postcode', models.IntegerField()),
                ('shipping_phonenumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('shipping_email', models.EmailField(max_length=254, unique=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.CharField(max_length=255)),
                ('billing', models.CharField(max_length=255)),
                ('total', models.IntegerField()),
                ('products', models.CharField(max_length=35)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=25)),
                ('payment_mode', models.CharField(max_length=35)),
                ('discount', models.IntegerField()),
                ('couponcode', models.CharField(max_length=5)),
                ('transaction_id', models.CharField(max_length=10)),
            ],
        ),
    ]
