# Generated by Django 4.2.7 on 2023-12-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_address_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='userid',
            field=models.IntegerField(default=1),
        ),
    ]
