# Generated by Django 4.2.7 on 2023-12-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_orders_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
