# Generated by Django 4.2.7 on 2023-12-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0027_alter_orders_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderid',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
