# Generated by Django 4.2.7 on 2023-12-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0028_orders_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderid',
            field=models.CharField(max_length=255),
        ),
    ]
