# Generated by Django 4.2.7 on 2023-12-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_alter_orders_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponname', models.CharField(max_length=6)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
