# Generated by Django 4.2.7 on 2023-12-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_rename_coupon_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='couponname',
            field=models.CharField(max_length=5),
        ),
    ]
