# Generated by Django 4.2.7 on 2023-12-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_alter_coupons_couponname'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupons',
            name='restriction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupons',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
    ]
