# Generated by Django 4.2.7 on 2023-12-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0034_alter_coupons_amount_alter_coupons_restriction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='token_id',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
