# Generated by Django 4.2.7 on 2023-12-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_registeruser_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='token_id',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
