# Generated by Django 4.2.7 on 2024-02-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0043_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(default=None, upload_to='products/image'),
        ),
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(default=None, upload_to='products/image'),
        ),
    ]
