# Generated by Django 4.2.7 on 2024-02-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0044_products_image2_products_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productdescription',
            field=models.TextField(default=False),
        ),
    ]
