# Generated by Django 4.2.7 on 2024-02-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0045_products_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productdescription',
            field=models.TextField(default=None),
        ),
    ]
