# Generated by Django 4.2.7 on 2024-02-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0046_alter_products_productdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Type',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
