# Generated by Django 4.2.7 on 2024-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0047_products_type_products_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
