# Generated by Django 4.2.7 on 2024-03-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0050_alter_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default=None, max_length=35),
        ),
    ]
