# Generated by Django 4.2.7 on 2024-03-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0056_alter_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('productreview', models.CharField(max_length=40)),
                ('star_rating', models.IntegerField()),
                ('productid', models.IntegerField()),
            ],
        ),
    ]
