# Generated by Django 4.2.7 on 2024-03-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0057_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='productreview',
            field=models.CharField(max_length=66),
        ),
    ]
