# Generated by Django 4.2.7 on 2024-03-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0059_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='userid',
            field=models.CharField(default=None, max_length=28),
        ),
    ]
