# Generated by Django 4.2.7 on 2024-03-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0060_remove_wishlist_price_wishlist_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
