# Generated by Django 4.2.7 on 2024-03-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0061_alter_wishlist_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='token_id',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
