# Generated by Django 4.2.7 on 2024-03-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0062_alter_registeruser_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productname',
            field=models.CharField(max_length=38),
        ),
    ]
