# Generated by Django 4.2.7 on 2024-04-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0063_alter_products_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
