# Generated by Django 4.2.7 on 2024-04-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0064_products_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
