# Generated by Django 4.2.7 on 2024-04-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0065_remove_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productname',
            field=models.CharField(max_length=40),
        ),
    ]
