# Generated by Django 4.2.7 on 2024-04-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0066_alter_products_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.CharField(max_length=40),
        ),
    ]
