# Generated by Django 4.2.7 on 2024-04-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0067_alter_orders_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='size',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
