# Generated by Django 4.2.7 on 2024-04-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0068_carts_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='size',
        ),
    ]
