# Generated by Django 4.2.7 on 2024-03-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
